version: '2'

services:
    limango:
        build: ./image
        image: limango
        restart: always
        volumes:
          - ./www:/var/www
          - ./config/nginx:/etc/nginx/sites-enabled
          - ./config/ssl:/etc/nginx/ssl
          - ./config/supervisor.conf:/etc/supervisor/conf.d/main.conf
        links:
          - redis
          - db
        ports:
          - "80:80"
          - "443:443"
    redis:
        image: redis
    db:   
      image: mysql:5.7
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: salwa
        MYSQL_DATABASE: mydb
        MYSQL_USER: rafal
        MYSQL_PASSWORD: salwa
      ports:
        - "9001:3306"

